<?php
// necesitamos la trayectoria de la URL para formar las rutas:
global $URL_PATH;
global $login_url;
\dawfony\Ti::extend("view/cabeceras/headerView.phtml");
\dawfony\Ti::endExtend();
?>
<body class="imagen-fondo-body" style="background-image: url('<?= $URL_PATH ?>/assets/fotosInterfaces/fondoBody.png');
    background-repeat: repeat;background-color: #fbf6f9;" onload="webpassOlvidadaLoad()">

    <div class="jumbotron">
        <header>
            <div class="img-container img-logo-vip">
                <img class="img-fluid img-logo " src="<?= $URL_PATH ?>/assets/fotosInterfaces/logo.png" data-srcpng="" alt="socialLoveLogo">
                <h1 class="img-logo logo-h1 ">SOCIAL LOVE</h1>
            </div>
        </header>
    </div>

    <div class="container passforget-principal" id="">

        <div class="passforget col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
            <div class="panel-info-pass">
                <div class="panel-head">
                    <div class="panel-title">Recuperar Password</div>
                    <div class="inicio-pass"><a href="<?= $URL_PATH ?>">Iniciar Sesi&oacute;n</a></div>
                </div>

                <div style="padding-top:30px" class="panel-body">

                    <form class="form-pass" action="<?= $URL_PATH ?>/restablecerPass" onsubmit="return passOlvidada(this)" method="POST" autocomplete="off">

                        <div style="margin-bottom: 20px" >
                                <b>INTRODUCE TU EMAIL:&nbsp;&nbsp;<span id="checkemail"></span></b>
                                <input id="email" type="email" class="form-control mail-pass" name="email" placeholder="ejemplo@gmail.com" onchange="recPassEmail()" required>
                        </div>
                        <div style="margin-left:15%;" id="captcha" class="g-recaptcha" data-sitekey="6LdAh-kUAAAAADqYGx69EMC6lMotjcKGVuatjmj6"></div>

                        <div style="margin-bottom:20px; margin-left:30%;" class="col-sm-5 controls">
                        
                            <button type="submit" id="preboton" class="btn btn-primary boton-confirm-tarjet pedido-btn btn-large" onclick="webpassOlvidadaLoader()">Enviar</button>
                        </div>
                        <div class="form-group">
                            <div class="col-md-12 control">
                                <div class="end-pass"> 
                                    No tienes una cuenta! <a href="#" onclick="location.href='<?= $URL_PATH ?>'">Registrate aqu&iacute;</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="loader6 mt-2" id="loaderpost"></span>
                                </div>             
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>


    <?php \dawfony\Ti::extend("view/cabeceras/footerView.phtml"); ?>
    <?php \dawfony\Ti::endExtend(); ?>
</body>


