<?php
// cuenta activada
use \dawfony\Ti;
global $URL_PATH;
global $login_url;
\dawfony\Ti::extend("view/cabeceras/headerView.phtml"); 
\dawfony\Ti::endExtend(); 
?>

<body class="imagen-fondo-body" style="background-image: url('<?= $URL_PATH ?>/assets/fotosInterfaces/fondoBody.png');background-repeat: repeat;background-color: #fbf6f9;">
    <!-- Hay que poner un guardado de COOKIES, que se activa si le damos al checked de guardar datos, si no una vez que cierre ventana tiene que volver a conectarse. -->
    <div class="container-fluid">
        <div class="container-fluid ">
            <!-- ********************** contenido ******************************************* -->
            <div class="container " style="background-color:white;width:80%;">
                <div class="row">
                    <div class="col-md-12 text-center"><br>
                        <div class="alert alert-light mb-2" role="alert">                            
                            <h2 class="text-center display-4 ml-3">Contraseña<span>
                                <svg id="m-check-mark" width="100px" height="50px" viewBox="0 0 245 173" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                                    <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd" stroke-opacity="0.7">
                                        <polyline id="checkmark" stroke="#ff69b4" stroke-width="15" points="5.640625 83.7607422 83.2539062 161.663086 238.97168 6.11328125"></polyline>
                                    </g>
                                </svg>
                            </span>Actualizada</h2><br>
                            <span><img style="display:flex;margin:0 auto;" width="25%" src="<?= $URL_PATH ?>/assets/fotosInterfaces/completado.png" alt="socialLoveLogo"></span>
                            <br>

                            <span class="lead">
                                Su contraseña ha sido correctamente actualizada. Muchas gracias.
                                <br><br>
                            </span>
                        </div>
                        <a class="btn btn-primary btn-large w-100 mt-0" href="<?= $URL_PATH ?>/">Iniciar sesion</a>
                    </div>
                </div><br>
            </div>
            <br>
            <?php Ti::extend("view/cabeceras/footerView.phtml"); ?>
            <?php Ti::endExtend(); ?>
        </div>
</body>