<?php
// necesitamos la trayectoria de la URL para formar las rutas:
global $URL_PATH;
global $login_url;
\dawfony\Ti::extend("view/cabeceras/headerView.phtml");
\dawfony\Ti::endExtend();
?>

<body class="imagen-fondo-body" style="background-image: url('<?= $URL_PATH ?>/assets/fotosInterfaces/fondoBody.png');
    background-repeat: repeat;
    background-color: #fbf6f9;">
    <?php
    \dawfony\Ti::extend("view/cabeceras/perfilView.phtml");
    \dawfony\Ti::endExtend();
    ?>
    <div class="container fondo-personas">
        <div class="grid-container-sesion container-fluid">
            <!-- ********************** Fotos de personas (chicas) imaginarias para hacer al usuario que se registre ******************************************* -->
            <?php foreach ($usuariosNotificados as $sacarLista) :  ?>
                <div class="container-images-sesion container-fluid">
                    <img class="imagenes-genero-sesion" src="<?= $URL_PATH ?>/assets/fotosUsuarios/fotos<?= $sacarLista['genero'] ?>s/<?= $sacarLista['foto'] ?>" alt="no_foto">
                    <!-- crear ruta para que nos lleve al perfil del usuario clickeado con su login-->
                    <a href="<?= $URL_PATH ?>/perfil/notificacion/<?= $sacarLista['login'] ?>">
                        <div class="middle">
                            <div class="text style-font">
                                <b><?= $sacarLista['login'] ?></b><br><?= $sacarLista['edad'] ?> años
                            </div>
                        </div>
                    </a>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
</body>
<?php \dawfony\Ti::extend("view/cabeceras/footerView.phtml"); ?>
<?php \dawfony\Ti::endExtend(); ?>