<?php

use dawfony\Ti;
global $URL_PATH;
/* extract($data); */
?>         
<div class="container-fluid">
            <footer class="rounded p-4 mt-2 text-center bg-footer myfont">
                <div>
                    <div class="grid-contador">
                        <div class="item1" id="contador"></div>
                        <div class="item2">
                            <div class="caja-footer footer-font-family">
                                <div class="img-container">
                                    <img class="img-fluid img-logo" src="<?= $URL_PATH ?>/assets/fotosInterfaces/logo.png" data-srcpng="" alt="socialLoveLogo">
                                    <h1 class="img-logo logo-h1">SOCIAL LOVE</h1>
                                </div>
                                <strong style="color:pink">SocialLove</strong> es una de las plataformas pioneras en unir personas. Su concepto innovador ha seducido a más de 25 millones, siendo de los únicos en garantizar el mismo número de chicas que de chicos.
                            </div>
                        </div>
                        <div class="item4"><i class="fa fa-facebook"></i>&nbsp;<i class="fa fa-twitter"></i>
                            <i class="fa fa-instagram"></i>&nbsp;<i class="fa fa-youtube"></i></div>
                        <div class="item5 footer-font-family">
                            <i class="fa fa-user"></i>&nbsp;Ángel Luis Fernández &nbsp;&nbsp;
                            <i class="fa fa-user"></i>&nbsp;Alberto Molina &nbsp;&nbsp;
                            <i class="fa fa-user"></i>&nbsp;Carlos Fernández
                        </div>
                    </div>
                </div>
                <br>
                © <?= date("Y") ?> 2ºDAW
            </footer>
        </div>