<?php

use dawfony\Ti;
global $URL_PATH;
global $login_url;
/* extract($data); */
?>
<div class="container-fluid">
            <div class="jumbotron">
                <header>
                    <!-- Aqui va el logo -->
                    <div class="img-container">
                        <img class="img-fluid img-logo" src="<?= $URL_PATH ?>/assets/fotosInterfaces/logo.png" data-srcpng="" alt="socialLoveLogo">
                        <a href="<?= $URL_PATH ?>/listado">
                        <h1 class="img-logo logo-h1">SOCIAL LOVE</h1>
                        </a>
                    </div>
                    <!-- Este es el navbar Hay que tocar a ver como podemos poner mejor los iconos y si podemos alargar el input -->
                    <nav class="navbar navbar-expand-lg navbar-dark  sesion">
                        <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
                            <ul class="mr-auto mt-2 mt-lg-0 navbar-nav sesion">
                                <li class="nav-item ">
                                    <a class="nav-link" href="<?= $URL_PATH ?>/correo" onclick=""><i class="fas fa-envelope"></i></a>
                                    <?php if ($_SESSION['notificacionesCorreo'] > 0) : ?>
                                            <span id="NotifyMail" class="num-notificaciones-correo"></span>
                                            <?php endif; ?>
                                </li>
                                &nbsp;
                                <li class="nav-item">
                                    <!-- falta hacer las notificaciones como el carrito compra que salga abajo si hay gente que te ha visitado -->
                                    <div class="header-mini-cart  pull-left open" id="formCompra">
                                        <span class="nav-link dropdown-toggle" height="70px" width="70px" href="javascript:void(0)" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-bell"></i></span>
                                        <?php if ($_SESSION['notificaciones'] > 0) : ?>
                                            <span class="num-notificaciones"></span>
                                            <?php endif; ?>
                                        <div class="dropdown-menu shopping-cart-content pull-right notificaciones">
                                            <div class="shopping-cart-items">
                                                <div class="lg-left">
                                                    <span class="span-notify style-font"><b>Te han hechizado</b></span>
                                                    <table class="style-font">
                                                        <tr>
                                                            <!-- Personas que han visto nuestro perfil lo sacamos luego cuando tengamos perfil...(no nos rayamos). -->
                                                            <!-- Cuidado que esta un tr y luego -->
                                                            <td><a href="<?= $URL_PATH ?>/notificaciones"><?= $_SESSION['notificaciones'] ?> PERSONA/s</a></td>
                                                            <td></td>
                                                            <td></td>
                                                        </tr>
                                                    </table>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                            <form  class="form-inline my-2 my-lg-1 formArreglo" action="<?= $URL_PATH ?>/busqueda" onsubmit="return validarBusqueda()" method="Get">
                                <input type="text" name="busquedaUsuario" id="busqueda" onkeypress="return buscarUsuario()" aria-label="Search" class="form-control form-control mr-sm-1" placeholder="Búsqueda por gustos,nombre,ubicacion o aficiones ">
                                <button type="submit" class="btn btn-outline-light my-2 my-sm-0"><i class="fas fa-search "></i></button>
                            </form>
                            <div class="header-mini-cart open modal-perfil" id="formCompra">
                                <img src="<?= $URL_PATH ?>/assets/fotosUsuarios/fotos<?= $_SESSION['genero'] ?>s/<?= $_SESSION["fotoPerfil"] ?>" class="imagen-perfil " href="javascript:void(0)" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <div class="dropdown-menu shopping-cart-content notificacion-perfil ">
                                    <div class="shopping-cart-items">
                                        <div class="lg-left">
                                            <span class="span-notify-perfil style-font"><b>Tu Perfil</b></span>
                                            <table class="style-font">
                                                <tr>
                                                    <!-- Falta adecuar bien el modal y que salga debajo no en el lado -->
                                                    <td><i class="fa fa-user"></i>&nbsp;&nbsp;Hola <?= $_SESSION["login"] ?></td>
                                                </tr>
                                                <tr>
                                                    <td><a class="perfil-enlace" href="<?= $URL_PATH ?>/zonavip"><i class="fas fa-magic"></i>&nbsp;&nbsp;Tienes <b style="color:pink" id="numHechizos"><?= $hechizos["hechizos"] ?></b> hechizos</a></td>
                                                </tr>
                                                <tr>
                                                    <td><i class="fas fa-star"></i><a class="perfil-enlace" href="<?= $URL_PATH ?>/perfil/<?= $_SESSION["login"] ?>">&nbsp;&nbsp;Ver Perfil</a></td>
                                                </tr>
                                                <tr>
                                                    <td><i class="fa fa-sign-out"></i><a class="perfil-enlace" href="<?= $URL_PATH ?>/logout">&nbsp;&nbsp;DESCONEXION</a></td>
                                                </tr>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </nav>
                </header>
            </div>
        </div>