<?php
// necesitamos la trayectoria de la URL para formar las rutas:
global $URL_PATH;
global $login_url;
/*facebookk*/
require_once('configfb.php');
$redirectTo = "http://localhost/sociallove/callbackphp"; //mandamos la peticion y a la vuelta va a este php
$dataFb = ['email'];
$fullURL = $handler->getLoginUrl($redirectTo, $dataFb);  //metemos el redirect y el email en fullURL
/*facebookk*/

\dawfony\Ti::extend("view/cabeceras/headerView.phtml");
\dawfony\Ti::endExtend();

?>

<body class="imagen-fondo-body" style="background-image: url('<?= $URL_PATH ?>/assets/fotosInterfaces/fondoBody.png');
    background-repeat: repeat;
    background-color: #fbf6f9;">
    <!-- Hay que poner un guardado de COOKIES, que se activa si le damos al checked de guardar datos, si no una vez que cierre ventana tiene que volver a conectarse. -->

    <!-- Si hay sesion iniciada por login -->
    <?php if (isset($_SESSION["login"])) : ?>
        <!-- ********************** Cabecera con jumbo y login ******************************************* -->
        <div class="container-fluid">
            <div class="jumbotron">
                <header>
                    <!-- Aqui va el logo -->
                    <div class="img-container">
                        <img class="img-fluid img-logo" src="<?= $URL_PATH ?>/assets/fotosInterfaces/logo.png" data-srcpng="" alt="socialLoveLogo">
                        <h1 class="img-logo logo-h1">SOCIAL LOVE</h1>
                    </div>
                    <!-- Este es el navbar Hay que tocar a ver como podemos poner mejor los iconos y si podemos alargar el input -->
                    <nav class="navbar navbar-expand-lg navbar-dark  sesion">
                        <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
                            <ul class="mr-auto mt-2 mt-lg-0 navbar-nav sesion">
                                <li class="nav-item ">
                                    <a class="nav-link" href="<?= $URL_PATH ?>/correo"><i class="fas fa-envelope"></i></a>
                                    <span>
                                        <!-- AQUI VA EL NUMERO DE NOTIFIACIONES RECIBIDAS, FONDO ROJO,NUMERO EN BLANCO,CON ANIMACION DE PARPADEO UNA VEZ ABIERTO DESAPARECE. --></span>
                                </li>
                                &nbsp;
                                <li class="nav-item">
                                    <!-- falta hacer las notificaciones como el carrito compra que salga abajo si hay gente que te ha visitado -->
                                    <div class="header-mini-cart  pull-left open" id="formCompra">
                                        <span class="nav-link dropdown-toggle" height="70px" width="70px" href="javascript:void(0)" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" onclick="verNotificaciones()"><i class="fas fa-bell"></i></span>
                                        <span>
                                            <!-- AQUI VA EL NUMERO DE NOTIFIACIONES RECIBIDAS, FONDO ROJO,NUMERO EN BLANCO,CON ANIMACION DE PARPADEO UNA VEZ ABIERTO DESAPARECE. --></span>
                                        <div class="dropdown-menu shopping-cart-content pull-right notificaciones">
                                            <div class="shopping-cart-items">
                                                <div class="lg-left">
                                                    <span class="span-notify style-font"><b>Han visto tu perfil</b></span>
                                                    <table class="style-font">
                                                        <tr>
                                                            <!-- Personas que han visto nuestro perfil lo sacamos luego cuando tengamos perfil...(no nos rayamos). -->
                                                            <!-- Cuidado que esta un tr y luego -->
                                                            <td> 0 PERSONA/s</td>
                                                            <td></td>
                                                            <td></td>
                                                        </tr>
                                                    </table>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                            <form class="form-inline my-2 my-lg-1" action="<?= $URL_PATH ?>/busqueda" onsubmit="return validarBusqueda()" method="Get">
                                <input type="text" name="busquedaUsuario" id="busqueda" onkeypress="return buscarUsuario()" aria-label="Search" class="form-control form-control mr-sm-1" placeholder="Búsqueda por gustos,nombre,ubicacion o aficiones ">
                                <button type="submit" class="btn btn-outline-light my-2 my-sm-0"><i class="fas fa-search "></i></button>
                            </form>
                            <div class="header-mini-cart open modal-perfil" id="formCompra">
                                <img src="<?= $URL_PATH ?>/assets/fotosUsuarios/fotos<?= $_SESSION['genero'] ?>s/<?= $_SESSION["fotoPerfil"] ?>" class="imagen-perfil " href="javascript:void(0)" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <div class="dropdown-menu shopping-cart-content notificacion-perfil ">
                                    <div class="shopping-cart-items">
                                        <div class="lg-left">
                                            <span class="span-notify-perfil style-font"><b>Tu Perfil</b></span>
                                            <table class="style-font">
                                                <tr>
                                                    <!-- Falta adecuar bien el modal y que salga debajo no en el lado -->
                                                    <td><i class="fa fa-user"></i>&nbsp;&nbsp;Hola <?= $_SESSION["login"] ?></td>
                                                </tr>
                                                <tr>
                                                    <td><a class="perfil-enlace" href="<?= $URL_PATH ?>/zonavip"><i class="fas fa-magic"></i>&nbsp;&nbsp;Tienes <b style="color:pink"><?= $hechizos["hechizos"] ?></b> hechizos</a></td>
                                                </tr>
                                                <tr>
                                                    <td><i class="fas fa-star"></i><a class="perfil-enlace" href="<?= $URL_PATH ?>/perfil/<?= $_SESSION["login"] ?>">&nbsp;&nbsp;Ver Perfil</a></td>
                                                </tr>
                                                <tr>
                                                    <td><i class="fa fa-sign-out"></i><a class="perfil-enlace" href="<?= $URL_PATH ?>/logout">&nbsp;&nbsp;DESCONEXION</a></td>
                                                </tr>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </nav>
                </header>
            </div>
        </div>
    <?php else : ?>
        <div class="container-fluid">
            <div class="jumbotron">
                <header>
                    <div class="clearfix">
                        <div class="img-container">
                            <img class="img-fluid img-logo" src="<?= $URL_PATH ?>/assets/fotosInterfaces/logo.png" data-srcpng="" alt="socialLoveLogo">
                            <h1 class="img-logo logo-h1">SOCIAL LOVE</h1>
                        </div>
                        <div class="img-container">
                            <?php $error_msg = $error_msg ?? ""; ?>

                            <?php if ($error_msg) : ?>
                                <script>
                                    Swal.fire({
                                        icon: 'error',
                                        type: 'info',
                                        title: 'Email o contraseña incorrecto.',
                                        timer: 3000,
                                        showConfirmButton: false
                                    });
                                </script>
                            <?php endif; ?>
                            <form class="form-inline" action="<?= $URL_PATH ?>/login" method="post">
                                <div class="form-group">
                                    <div class="form-group  mb-2">
                                        <input class="form-control form-control-sm" type="text" onchange="comprobarlogin()" id="mail" name="email" placeholder="correo electrónico" value="<?php if (isset($_COOKIE["usuario"])) : ?><?= $_COOKIE["usuario"]; ?> <?php endif ?>" required>
                                    </div>
                                    <div class="form-group mx-3 mb-2">
                                        <input class="form-control form-control-sm" type="password" id="password" name="password" value="<?php if (isset($_COOKIE["usuario"])) : ?><?= $_COOKIE["pass"] ?><?php endif ?>" placeholder="contraseña" required>
                                    </div>
                                    <div class="btn1">
                                        <button type="submit" id="btn-entrada-ok" class="btn btn-primary mb-2">OK</button>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="custom-control custom-checkbox mb-2">
                                        <input type="checkbox" class="custom-control-input" id="customCheck" name="rememberme" <?php if (isset($_COOKIE["usuario"])) : ?> checked <?php endif ?>>
                                        <label class="custom-control-label" for="customCheck"><span style="color:white">recordar mis datos</span></label>
                                    </div>
                                    <div class="form-group mx-5 ">
                                        <!-- Hacer la referencia por si ha olvidado la contraseña, mandar a una pagina y que saque su contraseña. -->
                                        <a class="password-lost-link white open-modal" href="<?= $URL_PATH ?>/passOlvidada">¿Has olvidado tu contraseña?</a>
                                    </div>
                                </div>

                            </form>
                        </div>
                    </div>
                </header>
            </div>
            <!-- ********************** Navbar para engaño del usuario para poder hacerse que se registre ******************************************* -->
            <nav class="navbar navbar-dark bg-dark navbar-expand-lg ">

                <ul class="navbar-nav mr-auto mt-2 mt-lg-0 navbar-center">
                    <li class="nav-item">
                        <a class="nav-link" href="#" data-toggle="modal" data-target="#modalContactForm" tabindex="-1">MUJERES</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#" data-toggle="modal" data-target="#modalContactForm" tabindex="-1">HOMBRES</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#" data-toggle="modal" data-target="#modalContactForm" tabindex="-1">NUEVA COLECCIÓN</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#" data-toggle="modal" data-target="#modalContactForm" tabindex="-1">NUESTRA SELECCIÓN</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#" data-toggle="modal" data-target="#modalContactForm" tabindex="-1">ESTILOS</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#" data-toggle="modal" data-target="#modalContactForm" tabindex="-1">GENTE DE TU REGIÓN</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#" data-toggle="modal" data-target="#modalContactForm" tabindex="-1"><i class="fas fa-search"></i>BÚSQUEDA</a>
                    </li>
                </ul>
            </nav>
            <div class="imagen-fondo">
                <div class="container-fluid ">
                    <div class="inscripcion cajaInscripcion">
                        <br>
                        <h1 class="style-font">Inscripción gratuita</h1>
                        <p class="style-font">en menos de un minuto</p>
                        <div class="">
                            <div class="text-center">
                                <a href="" class="btn btn-block mb-4 btn-social style-font btn btn-block mb-4 btn-flickr" id="fbook" data-toggle="modal" data-target="#modalContactForm"><img class="img-logo-inscripcion" src="<?= $URL_PATH ?>/assets/fotosInterfaces/logoIns.png" alt="socialLoveLogo">
                                    ME INSCRIBO</a>
                            </div>
                            <a href="<?= $login_url ?>" class="btn btn-block mb-4 btn-social btn-facebook style-font" id="fbook">
                                <i class="fa fa-facebook"></i> Conexión vía Facebook </a>

                        </div>
                    </div>
                </div>
            </div>
        <?php endif; ?>
        <?php /*****Aqui será el cuerpo *****/ ?>
        <?php \dawfony\Ti::startBlock("content"); ?>

        <?php \dawfony\Ti::endBlock(); ?>

        <!-- ********************** Modal registro ******************************************* -->
        <form action="<?= $URL_PATH ?>/postregistro" method="post" id="formuModal">
            <div class="modal fade" id="modalContactForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header text-center" style="background-color:#1c2228">
                            <h4 class="modal-title w-100 font-weight-bold style-font" style="color:white">Regístrate</h4>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true" style="color:White">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body body-register" style="background-image: url('<?= $URL_PATH ?>/assets/fotosInterfaces/fondoBody.png');
    background-repeat: repeat;
    background-color: #fbf6f9;">
                            <div class="md-form mb-3">
                                <i class="fas fa-venus-mars"></i>
                                <label for="register-sex" class="style-font">Género</label>
                                <select name="sex" id="register-sex" class="form-control form-control" onchange="genero()">
                                    <option value="X">yo soy...</option>
                                    <option value="chica">una mujer</option>
                                    <option value="chico">un hombre</option>
                                </select>

                            </div>
                            <div class="md-form mb-3">
                                <i class="fas fa-user prefix grey-text"></i>
                                <label for="prenombre" class="style-font">Nombre</label>
                                <input type="text" id="prenombre" class="form-control validate" name="prenombre" onkeyup="comprobarPreNombre()" required>

                            </div>
                            <div class="md-form mb-3">
                                <i class="fas fa-envelope prefix grey-text"></i>
                                <label for="email" class="style-font">E-mail &nbsp;&nbsp;<span id="checkemail"></span></label>
                                <input type="email" id="email" class="form-control validate" name="email" onkeyup="comprobaremail()" onchange="comprobaremail()" required>

                            </div>
                            <div class="md-form mb-3">
                                <i class="fas fa-lock"></i>
                                <label class="style-font">Contraseña</label>
                                <div class="input-group">
                                    <input id="txtPassword" type="password" class="form-control" name="prepassword" onchange="cssvalidarprePassword()" onkeydown="cssvalidarprePassword()" required>

                                    <div class="input-group-append">
                                        <button id="show_password" class="btn btn-dark" type="button" onclick="mostrarPassword()"> <span class="fa fa-eye-slash icon"></span> </button>
                                    </div>
                                </div>

                            </div>
                            <div class="md-form mb-3">

                                <i class="fas fa-calendar"></i>
                                <label class="style-font">Fecha Nacimiento</label><br>
                                <div class="grid-container-select-register">
                                    <select id="day" name="day" class="form-control form-control" onchange="cumpleD()">
                                        <option value="DD">DD</option>
                                        <option value="01">01</option>
                                        <option value="02">02</option>
                                        <option value="03">03</option>
                                        <option value="04">04</option>
                                        <option value="05">05</option>
                                        <option value="06">06</option>
                                        <option value="07">07</option>
                                        <option value="08">08</option>
                                        <option value="09">09</option>
                                        <option value="10">10</option>
                                        <option value="11">11</option>
                                        <option value="12">12</option>
                                        <option value="13">13</option>
                                        <option value="14">14</option>
                                        <option value="15">15</option>
                                        <option value="16">16</option>
                                        <option value="17">17</option>
                                        <option value="18">18</option>
                                        <option value="19">19</option>
                                        <option value="20">20</option>
                                        <option value="21">21</option>
                                        <option value="22">22</option>
                                        <option value="23">23</option>
                                        <option value="24">24</option>
                                        <option value="25">25</option>
                                        <option value="26">26</option>
                                        <option value="27">27</option>
                                        <option value="28">28</option>
                                        <option value="29">29</option>
                                        <option value="30">30</option>
                                        <option value="31">31</option>
                                    </select>
                                    <select id="month" name="month" class="form-control form-control" onchange="cumpleM()">
                                        <option value="MM">MM</option>
                                        <option value="1">01</option>
                                        <option value="2">02</option>
                                        <option value="3">03</option>
                                        <option value="4">04</option>
                                        <option value="5">05</option>
                                        <option value="6">06</option>
                                        <option value="7">07</option>
                                        <option value="8">08</option>
                                        <option value="9">09</option>
                                        <option value="10">10</option>
                                        <option value="11">11</option>
                                        <option value="12">12</option>
                                    </select>
                                    <select id="year" name="year" class="form-control form-control" onchange="cumpleY()">
                                        <option value="AA">AA</option>
                                        <option value="2002">2002</option>
                                        <option value="2001">2001</option>
                                        <option value="2000">2000</option>
                                        <option value="1999">1999</option>
                                        <option value="1998">1998</option>
                                        <option value="1997">1997</option>
                                        <option value="1996">1996</option>
                                        <option value="1995">1995</option>
                                        <option value="1994">1994</option>
                                        <option value="1993">1993</option>
                                        <option value="1992">1992</option>
                                        <option value="1991">1991</option>
                                        <option value="1990">1990</option>
                                        <option value="1989">1989</option>
                                        <option value="1988">1988</option>
                                        <option value="1987">1987</option>
                                        <option value="1986">1986</option>
                                        <option value="1985">1985</option>
                                        <option value="1984">1984</option>
                                        <option value="1983">1983</option>
                                        <option value="1982">1982</option>
                                        <option value="1981">1981</option>
                                        <option value="1980">1980</option>
                                        <option value="1979">1979</option>
                                        <option value="1978">1978</option>
                                        <option value="1977">1977</option>
                                        <option value="1976">1976</option>
                                        <option value="1975">1975</option>
                                        <option value="1974">1974</option>
                                        <option value="1973">1973</option>
                                        <option value="1972">1972</option>
                                        <option value="1971">1971</option>
                                        <option value="1970">1970</option>
                                        <option value="1969">1969</option>
                                        <option value="1968">1968</option>
                                        <option value="1967">1967</option>
                                        <option value="1966">1966</option>
                                        <option value="1965">1965</option>
                                        <option value="1964">1964</option>
                                        <option value="1963">1963</option>
                                        <option value="1962">1962</option>
                                        <option value="1961">1961</option>
                                        <option value="1960">1960</option>
                                        <option value="1959">1959</option>
                                        <option value="1958">1958</option>
                                        <option value="1957">1957</option>
                                        <option value="1956">1956</option>
                                        <option value="1955">1955</option>
                                        <option value="1954">1954</option>
                                        <option value="1953">1953</option>
                                        <option value="1952">1952</option>
                                        <option value="1951">1951</option>
                                        <option value="1950">1950</option>
                                        <option value="1949">1949</option>
                                        <option value="1948">1948</option>
                                        <option value="1947">1947</option>
                                        <option value="1946">1946</option>
                                        <option value="1945">1945</option>
                                        <option value="1944">1944</option>
                                        <option value="1943">1943</option>
                                        <option value="1942">1942</option>
                                        <option value="1941">1941</option>
                                        <option value="1940">1940</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer d-flex justify-content-center" style="background-color:#1c2228">
                            <button class="btn btn-unique style-font" id="preboton" type="submit" style="color:White" onclick="validarModal()">Enviar <i class="fas fa-paper-plane ml-1"></i></button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
        <?php \dawfony\Ti::extend("view/cabeceras/footerView.phtml"); ?>
        <?php \dawfony\Ti::endExtend(); ?>
</body>

</html>