<?php

use dawfony\Ti;

global $URL_PATH;
?>

<?php Ti::extend("view/MainView.phtml"); ?>

<?php Ti::startBlock("content"); ?>
<!-- Si hay sesion iniciada por login -->
<?php if (isset($_SESSION["login"])) : ?>

    <div class="container">
        <!-- ruta para conseguir mas hechizos al clikeo manda a otra pagina para ingresar email nuevo. -->
        <a href="<?= $URL_PATH ?>/hechizos/<?= $_SESSION["login"] ?>">
            <div class="imagen-fondo-sesion">
                <!-- Redireccionar para meter emails y consiga 10 hechizos -->
            </div>
        </a>
        <div class="container fondo-personas">
            <div class="grid-container-sesion container-fluid">
                <!-- ********************** Fotos de personas (chicas) imaginarias para hacer al usuario que se registre ******************************************* -->
                <?php foreach ($sacarLista as $sacarListaSesion) :  ?>
                    <div class="container-images-sesion container-fluid">
                        <img class="imagenes-genero-sesion" src="<?= $URL_PATH ?>/assets/fotosUsuarios/fotos<?= $sacarListaSesion->genero?>s/<?= $sacarListaSesion->foto ?>" alt="no_foto">
                        <!-- crear ruta para que nos lleve al perfil del usuario clickeado con su login-->
                        <a href="<?= $URL_PATH ?>/perfil/<?= $sacarListaSesion->login ?>">
                            <div class="middle">
                                <div class="text style-font">
                                    <b><?= $sacarListaSesion->login ?></b><br><?= $sacarListaSesion->edad ?> años<br> <?= $sacarListaSesion->ubicacion ?>
                                </div>
                            </div>
                        </a>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
        <nav aria-label="...">
            <ul class="pagination">
                <li class="page-item <?= ($pagina  <= 1 ? "disabled" : "") ?>">
                    <a class="page-link" href="<?= $ruta . ($pagina - 1) ?>" tabindex="-1" aria-disabled="true">Anterior</a>
                </li>
                <?php
                for ($i = 1; $i <= $numpaginas; $i++):?>

                    <li class="page-item ">
                        <a class="page-link" href="<?= $ruta ?><?= $i ?>"><?= $i ?></a>
                    </li>

                <?php
                    endfor;
                ?>
                <li class="page-item <?= ($pagina + 1 > $numpaginas ? "disabled" : "") ?>">
                    <a class="page-link" href="<?= $ruta . ($pagina + 1) ?>" aria-disabled="true">Siguiente</a>
                </li>
            </ul>
        </nav>
    </div>
    <!-- Aqui el nuevo cuerpo  que será igual asi pero quitando varias cosas y añadiendo otras -->
<?php else : ?>
    <div class="container-fluid container">
        <div class="container fondo-personas">
            <br>
            <hr>
            <p class="p-listado">ELLOS ESTÁN EN LA TIENDA</p>

            <!-- ********************** Fotos de personas (chicos) imaginarias para hacer al usuario que se registre ******************************************* -->
            <div class="grid-container-chicosFondo container">
                <a data-toggle="modal" data-target="#modalContactForm"><img src="<?= $URL_PATH ?>/assets/fotosInterfaces/tatuados.jpg" width="350px" height="350px" alt="tatuado"></a>
                <a data-toggle="modal" data-target="#modalContactForm"><img src="<?= $URL_PATH ?>/assets/fotosInterfaces/romanticos.jpg" width="350px" height="350px" alt="romantico"></a>
                <a data-toggle="modal" data-target="#modalContactForm"><img src="<?= $URL_PATH ?>/assets/fotosInterfaces/gafas.jpg" width="350px" height="350px" alt="gafas"></a>
            </div>
            <hr>
            <p class="p-listado">ELLAS TAMBIÉN ESTÁN EN LA TIENDA</p>
            <div class="grid-container-chicos container ">
                <!-- ********************** Fotos de personas (chicas) imaginarias para hacer al usuario que se registre ******************************************* -->
                <?php foreach ($sacarListaMenu as $sacarMujeresListaMenu) :  ?>
                    <div class="container-images">
                        <img class="grid-item imagenes-genero" src="<?= $URL_PATH ?>/assets/fotosUsuarios/fotosChicas/<?= $sacarMujeresListaMenu["fotos"] ?>" width="160px" height="160px" alt="chica1">
                        <a href="#" data-toggle="modal" data-target="#modalContactForm">
                            <div class="middle">
                                <div class="text style-font">
                                    <b><?= $sacarMujeresListaMenu["login"] ?></b><br><?= $sacarMujeresListaMenu["edad"] ?> años<br> <?= $sacarMujeresListaMenu["ubicacion"] ?>
                                </div>
                            </div>
                        </a>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
<?php endif; ?>
<?php Ti::endBlock(); ?>


<?php Ti::endExtend(); ?>